version: '3.4'
services:
  #backend
  app:
    container_name: weather
    env_file:
      - .env
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=aryan
      - MONGO_INITDB_ROOT_PASSWORD=123456789
  
  nginx:
    image: reverse-proxy
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-c   
    depends_on:
      - app
    ports:
      - "80:80"
  
  test:
    build: .
    command: npm test

